WebShop/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebShop.Core.Contracts;
using WebShop.Core.Models.Categories;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        public CategoryController(ICategoryService _categoryService)
        {
            categoryService = _categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(CategoryModel model)
        {
            await categoryService.AddNewCategory(model);

            return View();
        }

        public async Task<IActionResult> All()
        {
            var model = await categoryService.GetAllCategory();

            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var category = await categoryService.GetCategoryModelById(id);
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, CategoryModel model)
        {
            await categoryService.EditCategory(id, model);

            return RedirectToAction(nameof(All));
        }

    }
}

WebShop/Areas/Admin/Controllers/SubCategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebShop.Core.Contracts;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SubCategoryController : Controller
    {
        private readonly ISubCategoryService subCategoryService;
        public SubCategoryController(ISubCategoryService _subCategoryService)
        {
            subCategoryService = _subCategoryService;
        }

        public async Task<IActionResult> All(Guid id)
        {
            var model = await subCategoryService.GetAllSubCategory(id);

            return View(model);

        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var categoryId = await subCategoryService.DeleteSubCategory(id);

            return RedirectToAction("All", new { id = categoryId});
        }
    }
}

WebShop/Areas/Admin/Views/Category/Add.cshtml
@model CategoryModel

<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
    <form method="post">
        <fieldset>
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label text-light">Title</label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>            
            <br />
            <div id="DescriptionsContainer">
                @*<label asp-for="Description"></label>*@
                <a class="btn btn-outline-success text-light" style="margin-bottom: 10px" onclick="AddMoreSubCategory()">Add new description!</a>
            </div>
            <div class="mb-3">
                <input class="btn btn-primary" type="submit" value="Save" />
            </div>
        </fieldset>
    </form>
</div>
@section Scripts{
    <script>
        var subCategoryIndex = 0;
        function AddMoreSubCategory() {
            //var newInputs = $("Name <input type='text' name='' id=''/> Quantity <input type='text' name='' id=''/>");
            $("#DescriptionsContainer").append("<div class='mb-3 text-light'>Title <input type='text' name='SubCategories[" + subCategoryIndex + "].Name'/></div>");
            subCategoryIndex++;
        }
    </script>
}

WebShop/Areas/Admin/Views/Category/All.cshtml
@model IEnumerable<CategoryQueryModel>
@{
    ViewBag.Title = "All Category";
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">All categories</h3>
            </div>

            <div class="card-body table-responsive p-0 text-center justify-content-center">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>Category Name</th>
                            <th>Sub Category Count</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in Model)
                        {
                            <tr>
                                <td>@category.Name</td>
                                <td>@category.SubCategories.Count()</td>
                                <td>
                                    <a asp-area="Admin" asp-action="Edit" asp-controller="Category" asp-route-id="@category.Id" class="btn btn-block btn-outline-info btn-xs">Edit</a>
                                    <a asp-area="Admin" asp-action="All" asp-controller="SubCategory" asp-route-id="@category.Id" class="btn btn-block btn-outline-warning btn-xs">Sub Categories</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebShop/Areas/Admin/Views/Category/Edit.cshtml
@model CategoryModel

@{
    ViewBag.Title = "Edit Category";
}

<h2 class="text-center text-light">@ViewBag.Title</h2>
<hr />

<partial name="_CategoryPartial" model="@Model" />

@section Scripts{
        <script>
            var subCategoryIndex = 0;
            function AddMoreSubCategory() {
                //var newInputs = $("Name <input type='text' name='' id=''/> Quantity <input type='text' name='' id=''/>");
                $("#DescriptionsContainer").append("<div class='mb-3 text-light'>Title <input type='text' name='SubCategories[" + subCategoryIndex + "].Name'/></div>");
                subCategoryIndex++;
            }
        </script>
        <partial name="_ValidationScriptsPartial" />
}